# If you don't set these, they will be inferred from the repo's description on GitHub.

# title: My project title
# description: My description

theme: jekyll-theme-slate
title: Wessex Summer League 2023

github:
  is_project_page: false
